# Generated by slipway (cloud=azure, compute=aca, layer=app). Applied only by the CD workflow behind the environment approval.
terraform {
  required_version = ">= 1.9"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 5.0"
    }
  }

  backend "azurerm" {
    resource_group_name  = "rg-adlc-tfstate"
    storage_account_name = "stadlctfstate"
    container_name       = "tfstate"
    key                  = "adlc-demo/app/dev.tfstate"
    use_azuread_auth     = true
  }
}
